FROM       teneighty/libbitcoin-base
MAINTAINER Tim Horton <tmhorton@gmail.com>

RUN wget https://raw.githubusercontent.com/libbitcoin/libbitcoin-explorer/version2/install.sh
RUN chmod +x install.sh
RUN ./install.sh
