FROM       ubuntu:14.04
MAINTAINER Tim Horton <tmhorton@gmail.com>

RUN apt-get update && apt-get install -y build-essential autoconf automake \
                                         libtool pkg-config git wget \
                                         libboost1.55-all-dev libssl-dev
